### ISSUE TITLE
ELABORACION DEL WIKI PARA PRESENTACION

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pddcsharp#1]
Jóvenes de @tectijuana/patrones  elabora wiki de su patron a exponer.

**Comment by luisalavez** [comment]
decorator

**Comment by fabianvillatoro** [comment]
Mi tema es prototype

**Comment by paulinanoria** [comment]
Me toco Creación

**Comment by FoxtrotNov15** [comment]
Abstract factory

**Comment by rogelio28** [comment]
Mi temas es Patrón Adapter

**Comment by Neoceryx** [comment]
flyweight

**Comment by beatrizsoto** [comment]
Mi PDD es Visitor

**Comment by Jezreel20** [comment]
Tema: Composite

**Comment by JoelGarcia13** [comment]
Mi tema es el patron Template.

**Comment by EvelynMacedo** [comment]
Tema: Interpreter

**Comment by raulZepeda** [comment]
Aloha!

**Comment by ghost** [comment]
Patron state

**Comment by sarita23** [comment]
mi PDD es abstract factory

**Comment by EddyGaelMR** [comment]
MI TEMA ES Singleton

**Comment by Karenzuniga** [comment]
Patron bridge c#

**Comment by GermanVerdoza** [comment]
El mio es Mediator

**Comment by barajascesar** [comment]
PDD PROXY

**Comment by abrahamvazquez12** [comment]
El patrón Facade

**Comment by miguelnc93** [comment]
PDD Command

**Comment by anacruz5** [comment]
Me toco todo en general :)

**Comment by marcoafa** [comment]
Me toco Decorator

**Comment by enriquezazueta** [comment]
Patron Facade C#

**Comment by BrendaArellano** [comment]
Patrón Iterator C#

**Comment by aureliomeza** [comment]
El patrón Chain of Responsibility

**Comment by MarioLopezRodriguez** [comment]
Patron: Abstract factory

**Comment by raulZepeda** [comment]
Patron: factory Method

**Comment by Darij** [comment]
Patron Observer

**Comment by IoTeacher** [comment]
Hoy jueves este CASO (issue) se cerrará favor de poner su último dialogo de compromiso de exposicion de PDDC# por favor, al cerrarse quedara hay opción a un candado (LOCK) y no se puede abrir la conversación.

**Comment by abrahamvazquez12** [comment]
Profeso una duda no se que es lo que tengo que hacer específicamente me
indico que el tema que tenia que poner era estructural pero no encuentro
casi informacion es el por que son estructural

**Comment by IoTeacher** [comment]
@abrahamvazquez12 gracias por preguntar, primero sea tan amable de CROP a la foto de perfil para que aparezca Ud. nada mas, ahora referente a la estructura esta en el Ebook de Design Patterns en http://tinyurl.com/patrones16

**Comment by IoTeacher** [comment]
Jezreel20 commented 18 hours ago
PDD COmposite

**Comment by IoTeacher** [comment]
Gracias por exponer CSharp. Vamos por Java
