### ISSUE TITLE
Patron Observador

### ISSUE THREAD

**Issue by Darij** [tectijuana/pddcsharp#10]
19 de Febrero
Lopez Pesqueira Dario y Camacho Selvas Ulises

**Comment by Darij** [comment]
Profe, le aviso que otros 2 compañeros agarraron la misma fecha para exponer, que se puede hacer? nosotros somos el Issue #10

**Comment by IoTeacher** [comment]
Son 2 equipos por dia max.

**Comment by IoTeacher** [comment]
@Ulises-Camacho cambiar la foto por favor en junio poner el 8 bit pixel

**Comment by Darij** [comment]
@IoTeacher , mi companero no podra asistir a la escuela el dia hoy 19/febrero por complicaciones, podemos mover la fecha de exposicion? (de todos modos despues de investigar mas, resulta que el patron Observador es  un patron de Comportamiento en vez de  Estructura)

**Comment by Ulises-Camacho** [comment]
@IoTeacher ya cambie mi foto de perfil.

**Comment by Darij** [comment]
@IoTeacher Parece que no hay expo apartada para el dia 24, estaria bien exponer ese dia?

**Comment by IoTeacher** [comment]
@Ulises-Camacho  y @Darij  con 100 ambos gracias pero no corrieron el código. ojo
