### ISSUE TITLE
Patron memento

### ISSUE THREAD

**Issue by luisalavez** [tectijuana/pddcsharp#14]
23 de febrero
falta verificar el programa

**Comment by enriquezazueta** [comment]
### Compañero @luisalavez  si necesita ayuda le puedo brindar apoyo :+1:

**Comment by IoTeacher** [comment]
Gracias a ambos que dejan rastro de sus acuerdos en este módulo "issue" ![](http://i.imgur.com/bNm41H1.jpg)

**Comment by IoTeacher** [comment]
@luisalavez por el 100 !!
