### ISSUE TITLE
PD Comportamiento - Iterator

### ISSUE THREAD

**Issue by BrendaArellano** [tectijuana/pddcsharp#19]
El dia  **22 de Febrero** del 2016 Presento el Patrón de Diseño **Iterator** en C#

**Comment by EvelynMacedo** [comment]
Al 100, elegiste el mismo día que yo xD

**Comment by enriquezazueta** [comment]
Se olvidaron de @miguelnc93 , igual si terminan rapido pueden exponer 3 personas ese mismo dia :dancers: 
Soy Zazueta

**Comment by miguelnc93** [comment]
@enriquezazueta No, así esta bien :)

**Comment by EvelynMacedo** [comment]
Ya no se puede @enriquezazueta el docente fue muy explicito, dos días por personas :)

**Comment by IoTeacher** [comment]
Todo listo para presentación?

**Comment by BrendaArellano** [comment]
@IoTeacher Si listo, nos toca el lunes :)

**Comment by IoTeacher** [comment]
@BrendaArellano gacias por el 100.
