### ISSUE TITLE
Presentación del PDD

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pddcsharp#2]
Agradeciendo su valioso tiempo, paso a solicitar sean tan amable de _poner su foto y nombre con apellido paterno en su perfil del GIT_, recuerda que toda evidencia en el internet será la carta de presentación en las comunidades de desarrollo, _recomendable en App favorita en tu smartphone y con efectos lograrás poner un buen fondo y acomodarla en perfil_, como ejemplo te presento la foto del [http://twitter.com/IoTeacher](http://twitter.com/IoTeacher); la trabaje por unos minutos con AfterCut para Iphone.

Bien ya tenemos los directorios creados para dar un orden a la participación del los equipos a entregar funcionando sus evidencias de aprendizaje.

Cuentas con el WIKI que será la presentación del trabajo (no usamos powerpoint).

Recuerden crear su subdirectorio dentro del Patron, para que de una manera ordenana sea sincronizado el Repo. 
[Y muy recomendado las guia de Git en la guia oficial de GitHUB](https://guides.github.com/)

Gracias
@tectijuana/patrones

**Comment by enriquezazueta** [comment]
> **PDD Facade** : #1

**Comment by IoTeacher** [comment]
#1 Gracias

**Comment by IoTeacher** [comment]
@EvelynMacedo  le falto formatear el README.md para verlo presentable.

**Comment by BrendaArellano** [comment]
Es es que guste Pasar primero?? @enriquezazueta  seras primero??

**Comment by miguelnc93** [comment]
Según el que este listo puede pasar. O si no por lista de los **PDD**. **@BrendaArellano**

**Comment by BrendaArellano** [comment]
Gracias :+1:  @miguelnc93
