### ISSUE TITLE
PDD Command 25/02/2016

### ISSUE THREAD

**Issue by miguelnc93** [tectijuana/pddcsharp#24]
Expondré el 25 de febrero del 2016.

**Comment by IoTeacher** [comment]
Y como va con el tema? @miguelnc93

**Comment by miguelnc93** [comment]
Me falta estudiar y entender un poco mas el ejemplo. Estare listo para la fecha indicada :)  @IoTeacher

**Comment by IoTeacher** [comment]
@miguelnc93 Gracias con 100
