### ISSUE TITLE
PD prototype coop

### ISSUE THREAD

**Issue by FoxtrotNov15** [tectijuana/pddcsharp#28]
Me comprometo ayudar a mi compañero en el praton PROTOTYPE en donde explicare el diagrama del UML

**Comment by IoTeacher** [comment]
Le toca exponer @FoxtrotNov15 viernes.

**Comment by FoxtrotNov15** [comment]
Expone el dia 12/02/16 con el alumno Fabian Villatoro

**Comment by IoTeacher** [comment]
@FoxtrotNov15 tiene 100

**Comment by fabianvillatoro** [comment]
falto compannero de equipo carreon
