### ISSUE TITLE
Presentación del patrón de diseño: Template Method

### ISSUE THREAD

**Issue by JoelGarcia13** [tectijuana/pddcsharp#31]
Fecha: 25 de febrero del 2015
Integrantes: @joseOrduno y su servidor.

Notas: programa de ejemplo funcional en consola tomado del libro "Head First Design Patterns".

**Comment by IoTeacher** [comment]
@joseOrduno y @Joel13 tiene 100 en en la exposición.

**Comment by IoTeacher** [comment]
@Joel13 y @joseOrduno gracias por el 100.
