### ISSUE TITLE
Atencion

### ISSUE THREAD

**Issue by fabianvillatoro** [tectijuana/pddcsharp#38]
Revisando las carpetas, me de cuenta que algunos usuarios están modificando de una manera incorrecta y con esto se borran las carpetas de otros usuarios, afectando el trabajo de mucho, por eso pido revisar de manera correcta la subida de los documentos o carpetas desde la terminal.

Sin mas por el momento quedo a disposicion de un  dialogo para solventar el problema

**Comment by Neoceryx** [comment]
Acabo de revisar  el patron que Expuse (flyweight) Y borraron el archivo original que yo hice.
