### ISSUE TITLE
!. NO ESTEN BORRANDO LOS CODIGOS!

### ISSUE THREAD

**Issue by EvelynMacedo** [tectijuana/pddcsharp#39]
No se que estan haciendo pero estan borrando los trabajos de varias personas, no hagan eso. Nos van a perjudicar al momento de que el docente nos evalue.

**Comment by JoelGarcia13** [comment]
Al parecer eliminaron los archivos de unos siete u ocho patrones.

**Comment by ghost** [comment]
Yo por mi parte no eh podido subir mis patrones por que al quererlos subir con git, me dice que se hara un borrado de archivos al Github, mas no se como se pueda resolver este problema, dado que en caso de que haga un push al Github con lo que yo requiera subir se haria un borrado de todo lo anterior, no se que fue la persona responsable de ello, pero creo que sera lo mejor que se haga una revision del caso con el profesor @IoTeacher

**Comment by EvelynMacedo** [comment]
Si, porque no me parece justo que esten haciendo eso. Gracias por comentar compañeros :)

**Comment by IoTeacher** [comment]
@tectijuana/patrones

**Comment by Neoceryx** [comment]
Acabo de revisar el patron que Expuse (flyweight) Y borraron el archivo original que yo hice.
