### ISSUE TITLE
RUBRICA de la presentación

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pddcsharp#5]
## Caso #5 Calificación PDDCsharp  _(recordando que es el 50% de la evaluación bloque I, checar Tijuana.Education mas info.)_

Nombre, patrón y  día de presentación, calificación dará el docente en cuestion a la rubrica siguiente
![screen shot 2016-02-04 at 4 57 58 pm](https://cloud.githubusercontent.com/assets/2523851/12834926/7bc1bf5e-cb60-11e5-9716-bfd2f54fd994.png)
.

Dudas?
@tectijuana/patrones

**Comment by enriquezazueta** [comment]
**Gracias** Es de gran ayuda para estar _prevenidos_ en  #2 .

**Comment by IoTeacher** [comment]
@tectijuana/patrones Gracias se ha visto muy bien las presentaciones, y de los estudiantes alguno que otro con el facebook abierto con atencion a medias pero al final corren el código pero son pocos los casos @tectijuana/patrones
