### ISSUE TITLE
Stack issues

### ISSUE THREAD

**Issue by abrahamvazquez12** [tectijuana/pddcsharp#8]
No me reconoce iconos con el codigo de la pagina que nos brindo el profe de: **https://stackedit.io/editor**

**Comment by enriquezazueta** [comment]
> Solo hay que agregar el **_emoticon_** que se desea entre dos puntos al principio de este y al final, se le da un **preview**  y se identifica el **_emoticon_** :100: , :8ball: .
> #8

**Comment by luisalavez** [comment]
memento 23 de febrero
