### ISSUE TITLE
PD PROTOTYPE

### ISSUE THREAD

**Issue by fabianvillatoro** [tectijuana/pddcsharp#9]
LA EXPOSICIÓN DE PROTOTYPES ES PARA EL VIERNES 12 DE FEBRERO PERO  ME FALTA CORRER EL PROGRAMA

**Comment by IoTeacher** [comment]
@fabianvillatoro lo esperamos gracias.

**Comment by FoxtrotNov15** [comment]
exposicion realizada el dia lunes 15 de febrero con mi compañero @fabianvillatoro

**Comment by IoTeacher** [comment]
@fabianvillatoro con 100 calif
